"""Add captions to generated scenes

Revision ID: 11d45a4cb4a2
Revises: 98e4584dc844
Create Date: 2026-01-12 18:49:09.086778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11d45a4cb4a2'
down_revision: Union[str, Sequence[str], None] = '98e4584dc844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene', sa.Column('captions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scene', 'captions')
    # ### end Alembic commands ###
