"""Initial migrations

Revision ID: 2222268d4986
Revises: 
Create Date: 2026-01-09 21:30:12.013147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2222268d4986'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scene',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('visual_prompt', sa.Text(), nullable=True),
    sa.Column('mood', sa.String(length=20), nullable=True),
    sa.Column('audio_url', sa.String(length=255), nullable=True),
    sa.Column('audio_file_key', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('image_file_key', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scene')
    op.drop_table('video')
    # ### end Alembic commands ###
