"""Made video status an enum

Revision ID: 87c929a5ec95
Revises: f7153c72ae7e
Create Date: 2026-01-10 01:52:50.410423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '87c929a5ec95'
down_revision: Union[str, Sequence[str], None] = 'f7153c72ae7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


videostatus_enum = postgresql.ENUM(
    "pending",
    "processing",
    "completed",
    "failed",
    name="videostatus",
)


def upgrade() -> None:
    """Upgrade schema."""
    videostatus_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'processing', 'completed', 'failed', name='videostatus'),
               postgresql_using="status::videostatus",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'status',
               existing_type=sa.Enum('pending', 'processing', 'completed', 'failed', name='videostatus'),
               type_=sa.VARCHAR(length=20),
               postgresql_using="status::text",
               existing_nullable=False)
    # ### end Alembic commands ###
