"""Add audio duration seconds to scends model

Revision ID: 98e4584dc844
Revises: 9e50c71788b3
Create Date: 2026-01-12 09:19:10.369037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e4584dc844'
down_revision: Union[str, Sequence[str], None] = '9e50c71788b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene', sa.Column('audio_duration_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scene', 'audio_duration_seconds')
    # ### end Alembic commands ###
