"""Add final audio to video model

Revision ID: 9e50c71788b3
Revises: c98599e4a0d8
Create Date: 2026-01-10 10:04:49.622981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e50c71788b3'
down_revision: Union[str, Sequence[str], None] = 'c98599e4a0d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('final_audio_key', sa.String(length=255), nullable=True))
    op.add_column('video', sa.Column('final_audio_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'final_audio_url')
    op.drop_column('video', 'final_audio_key')
    # ### end Alembic commands ###
