"""cascade scenes

Revision ID: c98599e4a0d8
Revises: 3cc6e471af92
Create Date: 2026-01-10 02:17:01.379970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98599e4a0d8'
down_revision: Union[str, Sequence[str], None] = '3cc6e471af92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('scene_video_id_fkey'), 'scene', type_='foreignkey')
    op.create_foreign_key(None, 'scene', 'video', ['video_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scene', type_='foreignkey')
    op.create_foreign_key(op.f('scene_video_id_fkey'), 'scene', 'video', ['video_id'], ['id'])
    # ### end Alembic commands ###
