"""add files metadata

Revision ID: f7153c72ae7e
Revises: 2222268d4986
Create Date: 2026-01-09 21:36:23.805408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7153c72ae7e'
down_revision: Union[str, Sequence[str], None] = '2222268d4986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene', sa.Column('video_url', sa.String(length=255), nullable=True))
    op.add_column('scene', sa.Column('video_file_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scene', 'video_file_key')
    op.drop_column('scene', 'video_url')
    # ### end Alembic commands ###
